version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable all pull requests for GitHub Actions dependencies
    open-pull-requests-limit: 0

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable all pull requests for Docker dependencies
    open-pull-requests-limit: 0

