version: '3'

services:
  confluence:
    image: nicoherbigio/atlassian-confluence-server:latest
    restart: always
    depends_on:
      - confluence-database
    networks:
      - frontend
      - backend
    ports:
      - 8090:8090
      - 8091:8091
    volumes:
      - confluence-data:/var/atlassian/confluence
    environment:
      - JVM_MINIMUM_MEMORY=${CONFLUENCE_JVM_MINIMUM_MEMORY}
      - JVM_MAXIMUM_MEMORY=${CONFLUENCE_JVM_MAXIMUM_MEMORY}
      - CATALINA_CONNECTOR_SECURE=${CONFLUENCE_CONNECTOR_SECURE}
      - CATALINA_CONNECTOR_SCHEME=${CONFLUENCE_CONNECTOR_SCHEME}
      - CATALINA_CONNECTOR_PROXYNAME=${CONFLUENCE_CONNECTOR_PROXY_NAME}
      - CATALINA_CONNECTOR_PROXYPORT=${CONFLUENCE_CONNECTOR_PROXY_PORT}

  confluence-database:
    image: postgres:9.6
    restart: always
    networks:
      - backend
    volumes:
      - ./services/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - confluence-database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - CONFLUENCE_DATABASE_NAME=${CONFLUENCE_DATABASE_NAME}
      - CONFLUENCE_DATABASE_USER=${CONFLUENCE_DATABASE_USER}
      - CONFLUENCE_DATABASE_PASSWORD=${CONFLUENCE_DATABASE_PASSWORD}

networks:
  frontend:
  backend:

volumes:
  confluence-data:
  confluence-database-data:
