name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '7.4/**'
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-20.04]

    strategy:
      fail-fast: false
      matrix:
        version: [7.4, 7.13]
        include:
          - version: 7.4
            docker-context: 7.4/debian/default
            docker-tags: |
              nicoherbigde/atlassian-confluence-server:7.4
              nicoherbigio/atlassian-confluence-server:7.4
              nicoherbigde/atlassian-confluence-server:7.4.17
              nicoherbigio/atlassian-confluence-server:7.4.17
          - version: 7.13
            docker-context: 7.13/debian/default
            docker-tags: |
              nicoherbigde/atlassian-confluence-server:7.13
              nicoherbigio/atlassian-confluence-server:7.13
              nicoherbigde/atlassian-confluence-server:7.13.7
              nicoherbigio/atlassian-confluence-server:7.13.7

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push it to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          push: true
          tags: ${{ matrix.docker-tags }}
