name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '7.4/**'
      - '7.13/**'
      - '7.19/**'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-20.04]

    strategy:
      fail-fast: false
      matrix:
        version: [7.4-jammy, 7.13-jammy, 7.19-jammy]
        include:
          - version: 7.4-jammy
            docker-context: 7.4/ubuntu/default
            docker-tags: |
              nicoherbigde/atlassian-confluence-server:7.4
              nicoherbigde/atlassian-confluence-server:7.4-jammy
              nicoherbigde/atlassian-confluence-server:7.4.18
              nicoherbigde/atlassian-confluence-server:7.4.18-jammy
          - version: 7.13-jammy
            docker-context: 7.13/ubuntu/default
            docker-tags: |
              nicoherbigde/atlassian-confluence-server:7.13
              nicoherbigde/atlassian-confluence-server:7.13-jammy
              nicoherbigde/atlassian-confluence-server:7.13.11
              nicoherbigde/atlassian-confluence-server:7.13.11-jammy
          - version: 7.19-jammy
            docker-context: 7.19/ubuntu/default
            docker-tags: |
              nicoherbigde/atlassian-confluence-server:7.19
              nicoherbigde/atlassian-confluence-server:7.19-jammy
              nicoherbigde/atlassian-confluence-server:7.19.3
              nicoherbigde/atlassian-confluence-server:7.19.3-jammy

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push it to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          pull: true
          push: true
          tags: ${{ matrix.docker-tags }}
