name: Docker Image CI for version 6.13

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 1'

env:
  DOCKER_IMAGE_CONTEXT_PATH: 6.13/debian/default/
  DOCKERHUB_IMAGE_TAGS: |
    nicoherbigde/atlassian-confluence-server:6.13
    nicoherbigio/atlassian-confluence-server:6.13
    nicoherbigde/atlassian-confluence-server:6.13.4
    nicoherbigio/atlassian-confluence-server:6.13.4

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image and Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKER_IMAGE_CONTEXT_PATH }}
          push: true
          tags: ${{ env.DOCKERHUB_IMAGE_TAGS }}
